from datetime import timedelta

# JWT settings
SECRET_KEY = "SUPER_SECRET_KEY_CHANGE_ME"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

RESET_TOKEN_EXPIRE_MINUTES = 15
RESET_TOKEN_PURPOSE = "reset"